version: "3.9"

networks:
  propostas-network:
    driver: bridge

services:
  propostas-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - propostas-network

  propostas-api:
    build:
      dockerfile: Dockerfile
      context: .
    command: ["/wait-for-it.sh", "propostas-mysql:3306", "-t", "30", "-", "java", "-jar", "app.jar"]
    environment:
      DB_HOST: propostas-mysql
      DB_PASSWORD: 1234
      PROPOSAL_ANALYSIS_SERVICE: http://analise:9999
      ACCOUNTS_SERVICE: http://contas:8888
      DELAY_SCHEDULED_CARD_REQUESTS: 10000
      DELAY_PROPOSAL_ANALYSIS_REQUESTS: 30000
    ports:
      - "8080:8080"
    networks:
      - propostas-network
    depends_on:
      - propostas-mysql

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - propostas-network

  analise:
    image: 'zupacademy/analise-financeira'
    ports:
      - 9999:9999
    environment:
      SERVER_PORT: 9999
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - propostas-network

  contas:
    image: 'zupacademy/contas'
    ports:
      - 8888:8888
    environment:
      SERVER_PORT: 8888
      LOG_LEVEL: INFO
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - propostas-network