version: "3.9"

networks:
  propostas-network:
    driver: bridge

services:
  propostas-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - propostas-network

  propostas-api:
    build:
      dockerfile: Dockerfile
      context: .
    command: ["/wait-for-it.sh", "propostas-mysql:3306", "-t", "30", "-", "java", "-jar", "app.jar"]
    environment:
      APP_PORT: 8081
      DB_HOST: propostas-mysql
      DB_PASSWORD: 1234
      PROPOSAL_ANALYSIS_SERVICE: http://analise:9999
      ACCOUNTS_SERVICE: http://contas:8888
      DELAY_SCHEDULED_CARD_REQUESTS: 10000
      DELAY_PROPOSAL_ANALYSIS_REQUESTS: 30000
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/auth/realms/orange-talents
      KEYCLOAK_JWKS_URI: http://keycloak:8080/auth/realms/orange-talents/protocol/openid-connect/certs
    ports:
      - "8081:8081"
    networks:
      - propostas-network
    depends_on:
      - propostas-mysql

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - propostas-network

  analise:
    image: 'zupacademy/analise-financeira'
    ports:
      - 9999:9999
    environment:
      SERVER_PORT: 9999
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - propostas-network

  contas:
    image: 'zupacademy/contas'
    ports:
      - 8888:8888
    environment:
      SERVER_PORT: 8888
      LOG_LEVEL: INFO
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - propostas-network

  postgres:
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    networks:
      - propostas-network

  keycloak:
    image: jboss/keycloak
    ports:
      - 18443:8443
      - 8080:8080
      - 19990:9990
    depends_on:
      # Just a delay to wait for postgres! This is not recommended!
      - grafana
      - prometheus
      - jaeger
      #- kafka
      #- zookeeper
      - contas
      - analise
      #- transacoes
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      POSTGRES_PORT_5432_TCP_ADDR: 127.0.0.1
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth
    networks:
      - propostas-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-volume:/etc/prometheus/
    ports:
      - "9090:9090"
    network_mode: bridge

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
      - grafana-volume:/var/lib/grafana
    ports:
      - "3000:3000"
    network_mode: bridge
    depends_on:
      - prometheus

volumes:
  grafana-volume:
  prometheus-volume:
  postgres-volume: